# Site settings
title: Przemyslaw Magiera (beta website)
name: Przemyslaw Magiera

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/przemyslawmagiera
 - title: LinkedIn
   url: https://www.linkedin.com/prz-mag

#Any buzzword skills you want to include
skills:
 - Java 11
 - Spring Boot
 - JPA/Hibernate
 - JUnit/Mockito/TDD
 - Apache Solr
 - Elalasticsearch
 - Agile/Scrum
 - SQL
 - Docker
 - Machine Learning (begginer)
 - Bioinspired Algorithms (begginer)

#Work experience is required
roles:
 - title: Remote Java Developer
   start: 08.2019
   end: Ongoing
   employer: Antologic
   description: 
 - title: Java Developer (mid)
   start: 01.2019
   end: 08.2019
   employer: Solsoft
   description: 
 - title: Junior Java Developer
   start: 01.2017
   end: 12.2018
   employer: Solsoft
   description: 
   
#Education is required
education:
 - level: Master of Science (MSc)
   date: 2020
   subject: Advanced Computer Science
   school: University of Liverpool
 - level: Bachelor of Science (BSc.)
   date: 2019
   subject: Computer Science
   school: Wroclaw University of Science and Technology

#List of interesting Github repo/projects to include - optional
github:
 - przemyslawmagiera/genetic-algorithms-fun

intro: |
 Remote Java Developer, Student and Computer Science enthusiast. I have been programming commercially since 2016 and as a
 back-end developer I use Java language. After three years of experience I
 know how to write effective and clean code. I enjoy new challenges and that
 is why I decided to study in the foreign country. It has allowed me to explore
 new passions such as Bioinspired Learning and Data Science. I am used to
 working with different people in agile teams and I do think that one of the
 most powerful tools in software development is cooperation.
