# Site settings
title: Przemyslaw Magiera
twitter_username: rob_hinds
name: Przemyslaw Magiera

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/przemyslawmagiera
 - title: LinkedIn
   url: https://www.linkedin.com/prz-mag

#Any buzzword skills you want to include
skills:
 - Java 11
 - Spring Boot
 - Java
 - JPA/Hibernate
 - SQL
 - REST
 - JUnit/Mockito/TDD
 - Machine learning (begginer)
 - Bioinspired algorithms (begginer)

#Work experience is required
roles:
 - title: Remote Java Developer
   start: 08.2019
   end: Ongoing
   employer: Antologic
   description: Working remotely brings new challenges, but it lets me exploit my time more effectively, as I am still studying. As a developer my main task is to deliver business value to the project. I create, design and develop solutions, which then need to be implemented, what is in my scope of responsibilities as well.
- title: Java Developer (Mid)
   start: 01.2019
   end: 08.2019
   employer: Solsoft
   description: After finishing my Bachelor's Degree I got promoted to mid developer position. As a professional developer I was fully responsible for the quality and correctness of my code. My work demanded creativity an management skills, as well as excellent coding practices.
 - title: Junior Java Developer
   start: 01.2017
   end: 12.2018
   employer: Solsoft
   description: My first commercial position. I was happy to gain experience in small and local company, since such companies have a significant diversity of used technologies.
#Education is required
education:
 - level: Bachelor of Science (B.Sc.)
   date: 2003
   subject: Artificial Intelligence and Computer Science
   school: University of Birmingham


#List of interesting Github repo/projects to include - optional
github:
 - przemyslawmagiera/genetic-algorithms-fun

intro: |
Remote Java Developer, Student and Computer Science enthusiast in one
person. I have been programming commercially since 2016 and as a
back-end developer I use Java language. After three years of experience I
know how to write effective and clean code. I enjoy new challenges and that
is why I decided to study in the foreign country. It has allowed me to explore
new passions such as Bioinspired Learning and Data Science. I am used to
working with different people in agile teams and I do think that one of the
most powerful tools in software development is cooperation.

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
